<p style ="text-align:center">
    <img src="http://epecora.com.br/DataFiles/BannerUFPR.png" width="700" alt="PPGOLD/PPGMNE Python:INTRO"  />
</p>

## Prof. Eduardo Pécora, Ph.D.

# **Uma introducão ao Pandas**

Neste notebook cobriremos os seguintes tópicos:

1. [Introdução ao Pandas](#intro)
2. [Leitura de Dados](#data)

<a id="intro"></a>
# **Introdução ao Pandas**

**O que é o Pandas?**

O Pandas é uma biblioteca de código aberto que fornece ferramentas rápidas, flexíveis e expressivas para análise e manipulação de dados estruturados (principalmente em formato de tabela). Ele se destaca pela facilidade de uso e pela alta performance ao lidar com grandes volumes de dados, sendo amplamente utilizado em ciência de dados.

Pandas combina as melhores funcionalidades de várias ferramentas, como SQL (sintaxe de consultas), Excel (manipulação de tabelas) e arrays do NumPy (alta performance em operações numéricas). Seus principais objetivos incluem:
- Manipulação eficiente de grandes conjuntos de dados;
- Ferramentas para análise e agregação de dados;
- Integração fácil com bibliotecas de visualização e aprendizado de máquina, como Matplotlib, Seaborn e Scikit-learn.

**Estruturas de Dados do Pandas**

A biblioteca Pandas é construída em torno de duas principais estruturas de dados:
- `Series`: Uma estrutura de dados unidimensional, similar a um array do NumPy ou a uma lista do Python, mas com a capacidade de ter um índice associado. Cada elemento em uma Series tem um rótulo, que é o índice, o que permite um acesso mais eficiente.

Exemplo de `Series`:

In [9]:
import pandas as pd
import numpy as np

s = pd.Series([1, 3, 5, np.nan, 7, 9])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    7.0
5    9.0
dtype: float64

- `DataFrame`: A estrutura mais importante do Pandas, o `DataFrame`, é uma tabela bidimensional com dados organizados em linhas e colunas, semelhante a uma planilha ou a uma tabela SQL. Cada coluna em um DataFrame é uma `Series`, e o `DataFrame` é composto por uma coleção de `Series` alinhadas por índice.

Exemplo de `DataFrame` criado por meio de um dicionário, repare que os nomes das colunas são as chaves do dicionário.

In [10]:
data = {
    'Nome': ['Ana', 'Bruno', 'Carlos'],
    'Idade': [23, 35, 45],
    'Cidade': ['Curitiba','São Paulo', 'Rio de Janeiro']
}

df = pd.DataFrame(data)
print(df)

     Nome  Idade          Cidade
0     Ana     23        Curitiba
1   Bruno     35       São Paulo
2  Carlos     45  Rio de Janeiro

In [11]:
df.dtypes #Retorna os tipos de dados de cada coluna

Nome      object
Idade      int64
Cidade    object
dtype: object

`DataFrame` com datas nos índices.

In [12]:
dates = pd.date_range("20241107", periods=6)
print(dates)

DatetimeIndex(['2024-11-07', '2024-11-08', '2024-11-09', '2024-11-10',
               '2024-11-11', '2024-11-12'],
              dtype='datetime64[ns]', freq='D')

In [24]:
df2 = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print(df2.dtypes)
df2

A    float64
B    float64
C    float64
D    float64
dtype: object

                   A         B         C         D
2024-11-07  1.935245 -0.276053  0.125080 -0.440640
2024-11-08  0.778445 -0.694814  1.007127  1.509971
2024-11-09 -2.309142 -0.869434  0.257647 -0.722257
2024-11-10 -2.169900 -0.181826  0.971347  0.321142
2024-11-11  0.470302 -0.747137  1.460223  1.931470
2024-11-12  0.903468 -0.126654  0.776802  1.172747

In [14]:
df2.to_numpy() #Retorna o DataFrame como um array NumPy

array([[ 0.85642695, -0.33347107,  0.00916086, -2.50322835],
       [-0.43466342, -0.59912255,  1.48755571,  0.48748666],
       [-1.11144776,  0.10273433,  2.47436701,  0.81330448],
       [-1.1189228 , -1.72405633,  0.27283044,  0.92024643],
       [-0.99617218,  0.74483714,  0.33839757,  0.65134791],
       [-2.79929863, -1.36577998, -2.34356659,  1.68637746]])

In [15]:
df2.T #Retorna a transposta do DataFrame

   2024-11-07  2024-11-08  2024-11-09  2024-11-10  2024-11-11  2024-11-12
A    0.856427   -0.434663   -1.111448   -1.118923   -0.996172   -2.799299
B   -0.333471   -0.599123    0.102734   -1.724056    0.744837   -1.365780
C    0.009161    1.487556    2.474367    0.272830    0.338398   -2.343567
D   -2.503228    0.487487    0.813304    0.920246    0.651348    1.686377

<a id="data"></a>
# **Leitura de Dados**

A leitura de dados é o primeiro passo em qualquer fluxo de trabalho de análise de dados. O Pandas facilita a importação de dados de várias fontes e formatos para um DataFrame, que é a estrutura de dados principal utilizada ao longo da análise.

**Arquivos CSV**

O formato CSV (Comma-Separated Values) é um dos formatos de dados mais comuns, utilizado amplamente para armazenar dados tabulares.

In [16]:
nba_file = "https://raw.githubusercontent.com/EduPekUfpr/PythonProject/refs/heads/main/Dados/nba.csv" #caminho do arquivo

df_nba = pd.read_csv(nba_file)
print(df_nba.head())  # Exibe as primeiras 5 linhas do DataFrame

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

A função read_csv tem varios parâmetros, dentre os mais importantes temos:
- `sep`: Especifica o delimitador, caso o arquivo não utilize vírgulas;
- `header`: Indica a linha que contém os nomes das colunas;
- `names`: Define manualmente os nomes das colunas;
- `index_col`: Define uma coluna específica como índice do DataFrame;
- `usecols`: Carrega apenas as colunas especificadas;
- `dtype`: Especifica o tipo de dado para as colunas.

**Outros tipos de arquivo**

O pandas pode ler outros tipos de arquivo alem do CSV. Entre eles temos:
- Arquivos Excel, utilizando a função `read_excel()`;
- Arquivos JSON, utilizando a função `read_json()`;
- Arquivos SQL, utilizando a função `read_sql()`;
- Arquivos HTML, utilizando a função `read_html()`.

<a id="oper"></a>
# **Operações Básicas de Manipulação**

Após a leitura dos dados, o próximo passo é manipular esses dados para que fiquem prontos para análise. O Pandas fornece uma ampla gama de operações que facilitam a seleção, filtragem, modificação, reorganização e agregação de dados. Vamos explorar essas operações em detalhes.

## Visualizando os Dados

Antes de realizar qualquer manipulação, é importante inspecionar o DataFrame para entender sua estrutura e conteúdo.

In [17]:
df_nba.head(10)  # Exibe as primeiras 10 linhas

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

In [18]:
df_nba.tail(10)  # Exibe as últimas 10 linhas

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [19]:
df_nba.columns # Retorna as colunas no formato de uma lista

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [20]:
df_nba.index # Retorna os índices do DataFrame

RangeIndex(start=0, stop=457, step=1)

In [21]:
df_nba.info() #fornece um resumo conciso do DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [22]:
#Retorna estatísticas descritivas para colunas numéricas por padrão,
#incluindo contagem, média, desvio padrão, valores mínimo e máximo, e percentis.\
df_nba.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [23]:
#Retorna estatísticas descritivas para colunas numéricas e não numéricas
df_nba.describe(include = 'all')

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
count,457,457,457.000000,457,457.000000,457,457.000000,373,4.460000e+02
unique,457,30,NaN,5,NaN,18,NaN,118,NaN
top,Jeff Withey,New Orleans Pelicans,NaN,SG,NaN,6-9,NaN,Kentucky,NaN
freq,1,19,NaN,102,NaN,59,NaN,22,NaN
mean,NaN,NaN,17.678337,NaN,26.938731,NaN,221.522976,NaN,4.842684e+06
std,NaN,NaN,15.966090,NaN,4.404016,NaN,26.368343,NaN,5.229238e+06
min,NaN,NaN,0.000000,NaN,19.000000,NaN,161.000000,NaN,3.088800e+04
25%,NaN,NaN,5.000000,NaN,24.000000,NaN,200.000000,NaN,1.044792e+06
50%,NaN,NaN,13.000000,NaN,26.000000,NaN,220.000000,NaN,2.839073e+06
75%,NaN,NaN,25.000000,NaN,30.000000,NaN,240.000000,NaN,6.500000e+06
max,NaN,NaN,99.000000,NaN,40.000000,NaN,307.000000,NaN,2.500000e+07

## Fique Conectado

- [![YouTube](https://img.icons8.com/?size=40&id=19318&format=png&color=000000)](https://www.youtube.com/@LigaDataScience/videos)  
  Explore nossos vídeos educacionais e webinars sobre ciência de dados, machine learning e inteligência artificial. Inscreva-se para não perder nenhuma atualização!

- [![LinkedIn](https://img.icons8.com/?size=40&id=13930&format=png&color=000000)](https://www.linkedin.com/company/liga-data-science-ufpr/)  
  Siga-nos no LinkedIn para as últimas novidades, oportunidades de carreira e networking profissional no campo da ciência de dados.

- [![Instagram](https://img.icons8.com/?size=40&id=32323&format=png&color=000000)](https://www.instagram.com/ligadatascience/)  
  Confira nosso Instagram para conteúdos dos bastidores, destaques de eventos e o dia a dia da Liga Data Science. Faça parte da nossa jornada!
  
  
  ## Autores

<a href="https://www.linkedin.com/in/eduardopecora/" target="_blank">Eduardo Pecora</a>

<a href="https://www.linkedin.com/in/jo%C3%A3o-gabriel-santin-botelho-618244222/" target="_blank">João Gabriel Santin Botelho</a>


## Log de modificações

| Data | Versão | Modificado por | Descrição |
| ----------------- | ------- | ---------- | ---------------------------------- |
| 29-08-2024       | 1.0     | Eduardo Pecora & João Gabriel| Inicial               |

<hr>

## <h3 align="center"> (c) Liga Data Science/ UFPR 2024. All rights reserved. <h3/>