<p style ="text-align:center">
    <img src="http://epecora.com.br/DataFiles/BannerUFPR.png" width="700" alt="PPGOLD/PPGMNE Python:INTRO"  />
</p>

## Prof. Eduardo Pécora, Ph.D.


# **Pandas: Agrupamento de Dados**

Neste notebook cobriremos os seguintes tópicos:

1. [Agrupamento de dados](#oper)

<a id="data"></a>
# **Leitura de Dados**

A leitura de dados é o primeiro passo em qualquer fluxo de trabalho de análise de dados. O Pandas facilita a importação de dados de várias fontes e formatos para um DataFrame, que é a estrutura de dados principal utilizada ao longo da análise.

**Arquivos CSV**

O formato CSV (Comma-Separated Values) é um dos formatos de dados mais comuns, utilizado amplamente para armazenar dados tabulares.

In [1]:
import pandas as pd

nba_file = "nba.csv" #caminho do arquivo

df_nba = pd.read_csv(nba_file)
print(df_nba.head())  # Exibe as primeiras 5 linhas do DataFrame

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

## Agrupamento de Dados

Para análises mais avançadas, muitas vezes é necessário agrupar e agregar dados.

In [4]:
# Configura o formato para exibir números de ponto flutuante com duas casas decimais
pd.options.display.float_format = '{:.2f}'.format

#varias funções de agregação podem ser utilizadas, como mean(), count(), sum(), min(), max(), etc.

#PG = Point guard
#SG = Shooting guard
#SF = Small Forward
#PF = Power Forward
#C = Center

df_grouped = df_nba.groupby(['Position'])['Salary'].mean() # Média de todos os valores de salário para uma mesma posição
df_grouped

Position
C    5967052.00
PF   4562482.99
PG   5077829.22
SF   4857392.57
SG   4009861.19
Name: Salary, dtype: float64

In [7]:
df_grouped = df_nba.groupby(['Position'])['Salary'].count() # Conta de todos os valores de salário para uma mesma posição
df_grouped

Position
C     78
PF    97
PG    88
SF    84
SG    99
Name: Salary, dtype: int64

### Pivot Table

In [8]:
pd.pivot_table(df_nba, values=["Age"], index=["Team"], columns=["Position"], aggfunc='mean')

                         Age
Position                   C    PF    PG    SF    SG
Team
Atlanta Hawks          28.33 28.25 24.50 29.00 29.50
Boston Celtics         25.00 26.33 24.00 25.00 24.00
Brooklyn Nets          27.00 24.75 27.67   NaN 24.67
Charlotte Hornets      25.67 29.00 26.67 22.00 25.20
Chicago Bulls          33.00 24.80 29.00 24.00 28.75
Cleveland Cavaliers    28.33 30.00 27.33 33.00 30.00
Dallas Mavericks       29.67 31.25 31.50 27.50 25.50
Denver Nuggets         22.00 27.00 27.33 27.00 25.75
Detroit Pistons        28.00 28.50 27.50 22.75 25.50
Golden State Warriors  28.33 29.50 29.00 25.80 28.00
Houston Rockets        30.00 23.25 27.00 26.33 29.25
Indiana Pacers         28.50 24.00 27.75 26.67 26.00
Los Angeles Clippers   27.00 28.33 31.00 29.50 30.67
Los Angeles Lakers     26.67 25.00 25.67 31.75 29.00
Memphis Grizzlies      31.00 29.00 25.60 28.00 31.33
Miami Heat             26.00 32.50 26.50 29.00 26.67
Milwaukee Bucks        26.50 23.00 25.25 24.67 24.00
Minnesota Timberwolves 25.33 29.50 22.00 29.33 21.00
New Orleans Pelicans   29.33 26.67 26.75 27.00 25.60
New York Knicks        27.00 26.00 28.50 27.00 27.25
Oklahoma City Thunder  28.00 28.33 24.00 26.33 27.50
Orlando Magic          25.50 26.25 26.00 23.00 22.67
Philadelphia 76ers     21.00 26.60 25.00 23.50 23.50
Phoenix Suns           26.00 28.50 26.75 27.00 21.67
Portland Trail Blazers 29.00 21.33 27.50 24.00 24.40
Sacramento Kings       24.67 24.00 29.00 29.25 26.25
San Antonio Spurs      34.25 32.50 33.67 23.00 31.25
Toronto Raptors        23.33 30.25 26.00 24.67 24.50
Utah Jazz              25.00 24.00 23.25 26.67 23.50
Washington Wizards     30.67 30.00 27.50 25.50 27.25

In [9]:
pd.pivot_table(df_nba, values=["Age"], index=["College","Team"], columns=["Position"], aggfunc='count')

                               Age
Position                         C   PF   PG   SF   SG
College   Team
Alabama   Cleveland Cavaliers  NaN  NaN 1.00  NaN  NaN
          Memphis Grizzlies    NaN 1.00  NaN  NaN  NaN
          New Orleans Pelicans NaN  NaN  NaN 1.00  NaN
Arizona   Brooklyn Nets        NaN  NaN  NaN  NaN 1.00
          Cleveland Cavaliers  NaN 1.00  NaN 1.00  NaN
...                             ..  ...  ...  ...  ...
Wisconsin Houston Rockets      NaN  NaN  NaN 1.00  NaN
          Phoenix Suns         NaN 1.00  NaN  NaN  NaN
          Sacramento Kings     NaN 1.00  NaN  NaN  NaN
Wyoming   Los Angeles Lakers   NaN 1.00  NaN  NaN  NaN
Xavier    San Antonio Spurs    NaN 1.00  NaN  NaN  NaN

[336 rows x 5 columns]

## Fique Conectado

- [![YouTube](https://img.icons8.com/?size=40&id=19318&format=png&color=000000)](https://www.youtube.com/@LigaDataScience/videos)  
  Explore nossos vídeos educacionais e webinars sobre ciência de dados, machine learning e inteligência artificial. Inscreva-se para não perder nenhuma atualização!

- [![LinkedIn](https://img.icons8.com/?size=40&id=13930&format=png&color=000000)](https://www.linkedin.com/company/liga-data-science-ufpr/)  
  Siga-nos no LinkedIn para as últimas novidades, oportunidades de carreira e networking profissional no campo da ciência de dados.

- [![Instagram](https://img.icons8.com/?size=40&id=32323&format=png&color=000000)](https://www.instagram.com/ligadatascience/)  
  Confira nosso Instagram para conteúdos dos bastidores, destaques de eventos e o dia a dia da Liga Data Science. Faça parte da nossa jornada!
  
  ## Autores

<a href="https://www.linkedin.com/in/eduardopecora/" target="_blank">Eduardo Pecora</a>

<a href="https://www.linkedin.com/in/jo%C3%A3o-gabriel-santin-botelho-618244222/" target="_blank">João Gabriel Santin Botelho</a>

## Log de modificações

| Data | Versão | Modificado por | Descrição |
| ----------------- | ------- | ---------- | ---------------------------------- |
| 29-08-2024       | 1.0     | Eduardo Pecora & João Gabriel| Inicial               |

<hr>

## <h3 align="center"> (c) Liga Data Science/ UFPR 2024. All rights reserved. <h3/>